config/routes.rb
Rails.application.routes.draw do
  root to: 'cars#index'

  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  def index
    @car = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      created_message = "#{@car.year} #{@car.make} #{@car.model} created"
      redirect_to root_path,
        notice: created_message
    else
      error_message = "#{@car.errors.full_messages}"
      redirect_to root_path,
        notice: error_message
    end
  end

  def update
    updated_message = 'Car was successfully updated'
    @car.update(car_params)
    redirect_to root_path,
      notice: updated_message
  end

  def destroy
    @car.destroy
    redirect_to cars_url,
      notice: 'Car was successfully destroyed'
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year, :price)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= form_for(@car) do |form| %>

  <div>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <%= form.submit %>
<% end %>

app/views/cars/index.html.erb
<h1>Davinci Motors</h1>

<table>
  <thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
    <th colspan='3'></th>
  </tr>
  </thead>

  <tbody>
  <% @car.each do |car| %>
    <tr>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= number_to_currency(car.price) %></td>
      <td><%= link_to 'Show', car %></td>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Destroy', car,
          method: :delete,
          id: dom_id(car, 'Destroy'),
          data: {confirm: 'Are you sure?'}
      %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= form_for(@car) do |new_car| %>
  <div class="field">
    <%= new_car.label :make %>
    <%= new_car.text_field :make %>
  </div>

  <div class="field">
    <%= new_car.label :model %>
    <%= new_car.text_field :model %>
  </div>

  <div class="field">
    <%= new_car.label :price %>
    <%= new_car.text_field :price %>
  </div>

  <div class="field">
    <%= new_car.label :year %>
    <%= new_car.text_field :year %>
  </div>

  <div class="actions">
    <%= new_car.submit %>
  </div>
<% end %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<div>
  <strong>Make:</strong>
  <%= @car.make %>
</div>

<div>
  <strong>Model:</strong>
  <%= @car.model %>
</div>

<div>
  <strong>Year:</strong>
  <%= @car.year %>
</div>

<div>
  <strong>Price:</strong>
  <%= @car.price %>
</div>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DavinciMotors</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |flash_type, flash_message| %>
    <div class='flash' id='<%= flash_type %>'>
      <%= flash_message %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>